---
name: Scan Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-container:
    permissions:
      actions: read
      contents: read
      id-token: write
      pull-requests: write
      security-events: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-scan-container.yml@fix/dp-451-workflow-permissions 
    with:
      runtime: python
